name: Action Workflow

on: push

jobs:
  run-github-action:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls
      - name: Javascript Hello World Action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Urgain
      - name: Log Greeting time
        run: echo "${{steps.greet.outputs.time}}"
      - name: Action Checkout
        uses: actions/checkout@v3
      - name: List Files After checkout
        run: |
          pwd
          ls -a