name: Shell Commands

on: [push]

jobs:
  run_shell_command:
    runs-on: ubuntu-latest
    steps:
      - name: echo string
        run: echo "Hello. This is my first yaml program."
      - name: Multiline Commands
        run: |
          node -v
          python -v
      - name: Run python
        run: |
          import platform
          print(platform.processor())
        shell: python