name: Changing Node version

on: push

jobs:
  Node-version:
    strategy:
      matrix: 
        os: [macos-latest,ubuntu-latest,windows-latest]
        node-version: [12,14]
      # Include and Exclude was not working. So its commented out.
      # include:
      #   - os: ubuntu-latest
      #     node-version: 12
      #     is_ubuntu_12: true
      # exclude:
      #   - os: ubuntu-latest
      #     node-version: 14
      #   - os: macos-latest
      #     node-version: 12
      # max-parallel: 3
      fail-fast: true
    runs-on: ${{ matrix.os }}
    env: 
      IS_UBUNTU_12: ${{ matrix.is_ubuntu_12 }}
    steps:
      - name: node version
        run: node -v 
      - uses: actions/setup-node@v3
        with: 
          Node-version: ${{ matrix.node-version }}
      - name: node version after setup 
        run: |
          node -v
          echo $IS_UBUNTU_12